

version: 2.1
orbs:
  node: circleci/node@3.0.1
  heroku: circleci/heroku@1.2.6
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Build Docker image
          command: |
            docker build -t users-management-workshop:circleci .
            docker images
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Pushing to heroku registry
          command: |
            heroku container:login
            heroku container:push web --arg NODE_ENV=production -a $HEROKU_APP_NAME
            heroku container:release web -a $HEROKU_APP_NAME
workflows:
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

#version: 2.1
#orbs:
#  heroku: circleci/heroku@1.2.6
#workflows:
#  heroku_deploy:
#    jobs:
#      - heroku/deploy-via-git