#version: 2.1
#orbs:
#  node: circleci/node@5.0.2
#  heroku: circleci/heroku@1.2.6
#jobs:
#  build:
#    executor: node/default
#    steps:
#      - checkout
#      - node/install-packages
#      - setup_remote_docker:
#          version: 20.10.14
#      - run:
#          name: Build Docker image
#          command: |
#            docker build -t users-management-workshop:circleci .
#            docker images
#  deploy:
#    executor: heroku/default
#    steps:
#      - checkout
#      - heroku/install
#      - setup_remote_docker:
#          version: 20.10.14
#      - run:
#          name: Pushing to heroku registry
#          command: |
#            heroku container:login
#            heroku container:push web --arg NODE_ENV=production -a $HEROKU_APP_NAME
#            heroku container:release web -a $HEROKU_APP_NAME
#workflows:
#  build-deploy:
#    jobs:
#      - build
#      - deploy:
#          requires:
#            - build

#version: 2.1
#orbs:
#  node: circleci/node@5.0.2
#  heroku: circleci/heroku@1.2.6
#workflows:
#  heroku_deploy:
#    jobs:
#      - build
#      - heroku/deploy-via-git:
#          requires:
#            - build
#jobs:
#  build:
#    docker:
##      - image: circleci/node:10.16.0
#      - image: node:16.4.2-alpine
#    steps:
#      - checkout
#      - run:
#          name: Install dependencies
#          command: npm install



#version: 2.1
#orbs:
#  heroku: circleci/heroku@1.2.6
#workflows:
#  heroku_deploy:
#    jobs:
#      - heroku/deploy-via-git


version: 2.1
orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6
jobs:
  build:
    docker:
      - image: cimg/node:18.7.0
    steps:
      - checkout
      - node/install-packages
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Build Docker image
          command: |
            docker build -t users-management-workshop:circleci .
            docker images
workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            - build